# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

steps:
  # 1. adservice
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/online-boutique/adservice:latest', './src/adservice']
    waitFor: ['-']

  # 2. cartservice
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/online-boutique/cartservice:latest', './src/cartservice/src']
    waitFor: ['-']

  # 3. checkoutservice
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/online-boutique/checkoutservice:latest', './src/checkoutservice']
    waitFor: ['-']

  # 4. currencyservice
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/online-boutique/currencyservice:latest', './src/currencyservice']
    waitFor: ['-']

  # 5. emailservice
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/online-boutique/emailservice:latest', './src/emailservice']
    waitFor: ['-']

  # 6. frontend
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/online-boutique/frontend:latest', './src/frontend']
    waitFor: ['-']

  # 7. paymentservice
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/online-boutique/paymentservice:latest', './src/paymentservice']
    waitFor: ['-']

  # 8. productcatalogservice
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/online-boutique/productcatalogservice:latest', './src/productcatalogservice']
    waitFor: ['-']

  # 9. recommendationservice
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/online-boutique/recommendationservice:latest', './src/recommendationservice']
    waitFor: ['-']

  # 10. shippingservice
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/online-boutique/shippingservice:latest', './src/shippingservice']
    waitFor: ['-']

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/online-boutique/adservice:latest'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/online-boutique/cartservice:latest'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/online-boutique/checkoutservice:latest'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/online-boutique/currencyservice:latest'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/online-boutique/emailservice:latest'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/online-boutique/frontend:latest'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/online-boutique/paymentservice:latest'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/online-boutique/productcatalogservice:latest'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/online-boutique/recommendationservice:latest'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/online-boutique/shippingservice:latest'

options:
  machineType: 'E2_HIGHCPU_32'

timeout: '1800s'
